# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01193f9e7ceccdd4a1e38398b516dc8082afc23b7efaf019aec6232f2641c97fa75af43d5e6951f503c6aa610005a4d2c31fb2f2f44f6f375ed91dc5ab9c4295

test:
  secret_key_base: 2fb0c590d1a032815e8e62621ba0743dbf08c823db9af4380f2faa036ed2c1ad86c591849ee34dcf6947adfd4c5ff97046e7b24122b619577cc7282ad9b333bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
